# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 198)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.config_layout = QtWidgets.QVBoxLayout()
        self.config_layout.setObjectName("config_layout")
        self.import_connect_layout = QtWidgets.QHBoxLayout()
        self.import_connect_layout.setObjectName("import_connect_layout")
        self.connect_status_layout = QtWidgets.QHBoxLayout()
        self.connect_status_layout.setObjectName("connect_status_layout")
        self.connect_btn = QtWidgets.QPushButton(Dialog)
        self.connect_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.connect_btn.setObjectName("connect_btn")
        self.connect_status_layout.addWidget(self.connect_btn)
        self.status_label = QtWidgets.QLabel(Dialog)
        self.status_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.status_label.setObjectName("status_label")
        self.connect_status_layout.addWidget(self.status_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connect_status_layout.addItem(spacerItem)
        self.import_connect_layout.addLayout(self.connect_status_layout)
        self.config_layout.addLayout(self.import_connect_layout)
        self.exp_line_edit = QtWidgets.QLineEdit(Dialog)
        self.exp_line_edit.setText("")
        self.exp_line_edit.setObjectName("exp_line_edit")
        self.config_layout.addWidget(self.exp_line_edit)
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.config_layout.addWidget(self.line_8)
        self.exp_layout = QtWidgets.QHBoxLayout()
        self.exp_layout.setObjectName("exp_layout")
        self.ch_conf_layout = QtWidgets.QHBoxLayout()
        self.ch_conf_layout.setObjectName("ch_conf_layout")
        self.input_ch_layout = QtWidgets.QHBoxLayout()
        self.input_ch_layout.setObjectName("input_ch_layout")
        self.input_ch_label = QtWidgets.QLabel(Dialog)
        self.input_ch_label.setObjectName("input_ch_label")
        self.input_ch_layout.addWidget(self.input_ch_label)
        self.n_channel_label = QtWidgets.QLabel(Dialog)
        self.n_channel_label.setObjectName("n_channel_label")
        self.input_ch_layout.addWidget(self.n_channel_label)
        self.ch_conf_layout.addLayout(self.input_ch_layout)
        self.output_ch_layout = QtWidgets.QHBoxLayout()
        self.output_ch_layout.setObjectName("output_ch_layout")
        self.output_ch_label = QtWidgets.QLabel(Dialog)
        self.output_ch_label.setObjectName("output_ch_label")
        self.output_ch_layout.addWidget(self.output_ch_label)
        self.output_ch_input = QtWidgets.QSpinBox(Dialog)
        self.output_ch_input.setMinimum(1)
        self.output_ch_input.setMaximum(15)
        self.output_ch_input.setProperty("value", 6)
        self.output_ch_input.setObjectName("output_ch_input")
        self.output_ch_layout.addWidget(self.output_ch_input)
        self.ch_conf_layout.addLayout(self.output_ch_layout)
        self.exp_layout.addLayout(self.ch_conf_layout)
        self.config_layout.addLayout(self.exp_layout)
        self.verticalLayout.addLayout(self.config_layout)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.connect_btn.setText(_translate("Dialog", "Conectar"))
        self.status_label.setText(_translate("Dialog", "Status"))
        self.exp_line_edit.setPlaceholderText(_translate("Dialog", "Experimento #"))
        self.input_ch_label.setText(_translate("Dialog", "Input Channels:"))
        self.n_channel_label.setText(_translate("Dialog", "1"))
        self.output_ch_label.setText(_translate("Dialog", "Output Channels:"))
